project:
  type: website

website:
  title: "Digital Archaeology Maintainathon"
  site-url: https://sslarch.github.io/maintainathon/
  favicon: images/sig_ssla_logo.svg

  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/), with theme from [vetiver](https://github.com/rstudio/vetiver.rstudio.com) and inspired by [NASA Openscapes](https://openscapes.org/)."
    left: "Brought to you by the [Scientific Scripting Languages in Archaeology SIG](https://sslarch.github.io/)"

  navbar:
    logo: images/sig_ssla_logo.svg
    href: https://sslarch.github.io/maintainathon/
    right:
    - text: "Resources"
      href: resources.qmd
    - text: "Showcase"
      href: showcase.qmd
    - icon: github
      href: https://github.com/sslarch/maintainathon
    - icon: mastodon
      href: https://archaeo.social/@CAA_SSLA
format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left

